# minimal mistakes Jekyll reference
# https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml

remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "air"

title: "rnext"
subtitle: "Robotics & Automation"
name: &name "Raffaello Bonghi"
description: &description "Raffaello Bonghi personal website"
url: https://rbonghi.github.io
repository: "rbonghi/rbonghi.github.io"
teaser: /assets/images/intro.jpg

search: true
search_full_content: true

twitter:
  username: &twitter "raffaello86"

social:
  links: # An array of links to social media profiles
    - "https://twitter.com/raffaello86"
    - "https://instagram.com/robo.panther"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-92957365-1"
    anonymize_ip: false # default
  google-tag:
    tracking_id: "GTM-NQ934NG"

#maps:
#  google:
#    api_key: AIzaSyDoyC-cqye7jnmLaKjWzc2txBVzL0wU-7A

author:
  name        : "Raffaello Bonghi"
  bio         : "Passion Robotics. Working in Robotics & AI. Ah Yes, in my spare time I work in robotics. Ph.D. in Robotics and automation engineer"
  avatar      : "/assets/images/raffaello.jpg"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/raffaello86"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/raffaello-bonghi/"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/rbonghi"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/c/RaffaelloBonghi"
    - label: "IG Personal"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/raffaello86"
    - label: "IG Tech"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/robo.panther"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:raffaello@rnext.it"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/raffaello86"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/raffaello-bonghi/"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/rbonghi"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/c/RaffaelloBonghi"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/raffaello86"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:raffaello@rnext.it"
    - label: "Terms"
      icon: "fas fa-fw fa-link"
      url: "/terms"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - README.md
  - LICENSE
  - Gemfile

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

collections:
  robot:
    output: true
    permalink: /:collection/:path/
  project:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      show_date: true
  # _robot
  - scope:
      path: ""
      type: robot
    values:
      layout: single
      author_profile: true
      share: true
      read_time: true
  # _project
  - scope:
      path: ""
      type: project
    values:
      layout: single
      author_profile: true
      share: true
      read_time: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
#  - jekyll-maps

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
#  - jekyll-maps

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

after_footer_scripts :
  - /assets/js/cookie-consent.js
